
version: "3.9"
services:
  sejam-react:
    image: 172.24.65.12:81/repository/tech1a-docker-registry/sejam-react:latest
    networks:
      - omsnet
    ports:
      - 9075:3000

    deploy:
      mode: replicated
      replicas: 1    
      update_config:
        parallelism: 5
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
        window: 20s
networks:
 omsnet:
    external:
      name: omsnet
