kind: ConfigMap
apiVersion: v1
metadata:
  name: sejam-react
  labels:
    name: sejam-react
    instance: sejam-react
data:
  SEJAM_URL: "https://sejam-gateway.tavanabroker.ir"
  IDP_URL: "https://idp.tavanabroker.ir"
  FILE_SERVER_URL: "https://file-manager.tavanabroker.ir"
  CAPTCHA_URL: "https://captcha.tavanabroker.ir"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejam-react
spec:
  selector:
    matchLabels:
      app: sejam-react
  replicas: 1
  template:
    metadata:
      labels:
        app: sejam-react
    spec:
      containers:
      - name: sejam-react
        image: "registry.tech1a.co:81/repository/tech1a-docker-registry/sejam-react:latest"
        envFrom:
          - configMapRef:
              name: sejam-react
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sejam-react
  labels:
    app: sejam-react
spec:
  type: ClusterIP
  selector:
    app: sejam-react
  ports:
    - port: 443
      protocol: TCP
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sejam-react
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sejam.tavanabroker.ir
    secretName: tavana-ir
  rules:
    - host: sejam.tavanabroker.ir
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sejam-react
              port:
                number: 443


